[2022-05-14 20:34:55,245: INFO/ForkPoolWorker-1] [download start] sleep: 3.0 01PavanePourUneInfanteDfuntePourPianoMr19.mp3
[2022-05-14 20:35:27,333: INFO/ForkPoolWorker-1] [download finished] 01PavanePourUneInfanteDfuntePourPianoMr19.mp3
[2022-06-07 19:20:54,749: WARNING/MainProcess] /Users/kazuyaaoki/.pyenv/versions/3.10.3/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:367: CPendingDeprecationWarning: 
In Celery 5.1 we introduced an optional breaking change which
on connection loss cancels all currently executed tasks with late acknowledgement enabled.
These tasks cannot be acknowledged as the connection is gone, and the tasks are automatically redelivered back to the queue.
You can enable this behavior using the worker_cancel_long_running_tasks_on_connection_loss setting.
In Celery 5.1 it is set to False by default. The setting will be set to True by default in Celery 6.0.

  warnings.warn(CANCEL_TASKS_BY_DEFAULT, CPendingDeprecationWarning)

